# Setup
title:        Frederik Van den Broeck
tagline:      A personal website keeping stuff
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Frederik Van den Broeck
  url:        ""

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
theme: jekyll-theme-cayman
