# Site wide configuration
title:        Frederik Van den Broeck w/ GitHub Blog
author:       Frederik Van den Broeck
locale:       en_US
description:  Information about me, PhD, Projects, Research lines, Blogs, Scripts, programs, parasite evolution and hybridization - neglected tropical diseases - evolutionary genomics - bioinformatics
url:          https://frebio.github.io
search:       true
twitter:      FBroeck
baseurl:      https://frebio.github.io
google_analytics: https://frebio.github.io


# Site owner
owner:
  name: Frederik Van den Broeck
  avatar: images/IDsmall.JPG
  email: fvandenbroeck@email.com
  disqus-shortname: Fre
  twitter: FBroeck
  github: FreBio
  
# Others
markdown: kramdown
theme: jekyll-theme-cayman
