# Site wide configuration
title:        Frederik Van den Broeck
locale:       en_US
description:  I am a post-doctoral researcher at the Department of Biomedical Sciences in the Antwerp Institute of Tropical Medicine. I am mainly interested in eukaryotic parasites causing Neglected Tropical Diseases that seriously reduce childhood survival rates within the poorest regions of Africa, Asia and South-America.  biologist - tropical diseases - parasite evolution & hybridization - evolutionary genomics
logo:         images/IDsmall.JPG
search:       true
baseurl:      ""

# Site owner
owner:
  name: Frederik Van den Broeck
  avatar: images/IDsmall.JPG
  email: fvandenbroeck@email.com
  disqus-shortname: Fre
  twitter: FBroeck
  github: FreBio
  
#Others
markdown: kramdown
theme: jekyll-theme-cayman
