# Site wide configuration
# title:        Frederik Van den Broeck
locale:       en_US
# description:  parasite evolution and hybridization - neglected tropical diseases - evolutionary genomics - bioinformatics
search:       true
baseurl:      ""
google_analytics:

gems:
  - jekyll-seo-tag

# Site owner
owner:
  name: Frederik Van den Broeck
  avatar: images/IDsmall.JPG
  email: fvandenbroeck@email.com
  disqus-shortname: Fre
  twitter: FBroeck
  github: FreBio
  
#Others
markdown: kramdown
theme: jekyll-theme-cayman
