# Site wide configuration
title:        Frederik Van den Broeck
locale:       en_US
description:  biologist - tropical diseases - parasite evolution & hybridization - evolutionary genomics
logo:         images/IDsmall.JPG
search:       true
baseurl:      ""

# Site owner
owner: Frederik Van den Broeck
  name: Frederik Van den Broeck
  avatar: images/IDsmall.JPG
  email: fvandenbroeck@email.com
  disqus-shortname: Fre
  twitter: FBroeck
  github: FreBio
  
#Others
markdown: kramdown
theme: jekyll-theme-cayman
